controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

      ros__parameters:
        publish_rate: 50.0
        base_frame_id: base_link
        left_wheel_names: ["left_wheel_joint"]
        right_wheel_names: ["right_wheel_joint"]
        wheel_separation: 0.3  # Distance between wheels (adjust based on URDF)
        wheel_radius: 0.1     # Radius of wheels (from URDF)
        use_stamped_vel: false
        pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
        twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
        open_loop: false
        enable_odom_tf: true
        odom_frame_id: odom
        odom_topic: /odom

        # PID gains for velocity control (tune these)
        pid_gains:
          left_wheel_joint: {p: 1.0, i: 0.0, d: 0.1}
          right_wheel_joint: {p: 1.0, i: 0.0, d: 0.1}
